mats = {'Stat_09_02_01.mat',...
    'Stat_09_02_02.mat',...
    'Stat_09_02_03.mat'};
CPGns = {'2-level-V2',...
    '1-level',...
    '2-level-V1'};
for i = 1:numel(mats)
    clear Experts Averages
    load(mats{i})
    CPGName = CPGns{i};
    save(mats{i},'Experts','Averages','CPGType','CPGName','Volumes');
end