mats = {'Stat_09_21_21.mat',...
    'Stat_09_21_22.mat',...
    'Stat_09_21_23.mat'};
CPGns = {'1-level',...
    '2-level',...
    'Hybrid'};
for i = 1:numel(mats)
    clear Experts Averages CPGType CPGName fcount fcountchild fcountrandom Areas lowAnkPer
    load(mats{i})
    CPGName = CPGns{i};
    save(mats{i},'Experts','Averages','CPGType','CPGName','fcount','fcountchild','fcountrandom','Areas','lowAnkPer');
end